apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"24","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/cloudian cloudian=10.81.1.50:5000/cloudian:21 --record=true"},"creationTimestamp":"2020-10-19T13:16:17Z","generation":25,"labels":{"io.kompose.service":"cloudian"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"cloudian\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"ACTIVE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"CLIENT_ADMIN\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"CLOUDIAN\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENDPOINT_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENV_CHECK\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"GROUPID\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LDAP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOG_TARGET\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_SECRET_KEY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PASSWORD\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PYTHONUNBUFFERED\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"USERADMIN\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"USERNAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"USERSTATUS\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"USERTYPE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"USERTYPES\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8002,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:20:16Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:20:23Z"}],"name":"cloudian","namespace":"default","resourceVersion":"27900740","selfLink":"/apis/apps/v1/namespaces/default/deployments/cloudian","uid":"273cbe7f-1113-474c-a925-3e6f858daa54"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"cloudian"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"cloudian"}},"spec":{"containers":[{"env":[{"name":"CLOUDIAN","value":"https://10.81.1.55:19443"},{"name":"ENDPOINT_URL","value":"http://10.81.1.55:80/"},{"name":"USERTYPE","value":"User"},{"name":"LDAP","value":"false"},{"name":"ACTIVE","value":"true"},{"name":"USERNAME","value":"sysadmin"},{"name":"PASSWORD","value":"public"},{"name":"CLIENT_ADMIN","value":"client_admin"},{"name":"USERADMIN","value":"SystemAdmin"},{"name":"GROUPID","value":"0"},{"name":"USERSTATUS","value":"active"},{"name":"USERTYPES","value":"all"},{"name":"MS_LOGGER_THIS_SERVICE_NAME","value":"cloudian"},{"name":"MS_LOGGER_THIS_SERVICE_IP","value":"cloudian"},{"name":"MS_LOGGER_THIS_SERVICE_PORT","value":"8002"},{"name":"MS_LOGGER_IP","value":"ms-logger"},{"name":"MS_LOGGER_PORT","value":"8012"},{"name":"MS_LOGGER_SECRET_KEY","value":"BC2B36B81AB89F3B83AD227DCAD56"},{"name":"PYTHONUNBUFFERED","value":"0"},{"name":"LOG_TARGET","value":"both"},{"name":"ENV_CHECK","value":"production"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"}],"image":"10.81.1.50:5000/cloudian:21","imagePullPolicy":"IfNotPresent","name":"cloudian","ports":[{"containerPort":8002,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-02-16T11:46:13Z","lastUpdateTime":"2021-02-16T11:46:13Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-01-14T07:14:39Z","lastUpdateTime":"2021-03-03T11:20:23Z","message":"ReplicaSet \"cloudian-78b7c67f5d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":25,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/cloudian cloudian=10.82.3.2:5000/cloudian:23
      --record=true
  creationTimestamp: "2021-03-15T07:09:02Z"
  generation: 3
  labels:
    io.kompose.service: cloudian
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"cloudian"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ACTIVE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"CLIENT_ADMIN"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CLOUDIAN"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ENDPOINT_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ENV_CHECK"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"GROUPID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LDAP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PYTHONUNBUFFERED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERADMIN"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERSTATUS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERTYPE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERTYPES"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8002,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:02Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"cloudian"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:09:39Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"cloudian"}:
                f:env:
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T10:37:21Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:06Z"
  name: cloudian
  namespace: default
  resourceVersion: "2198106"
  selfLink: /apis/apps/v1/namespaces/default/deployments/cloudian
  uid: 208f5538-decc-41de-9e4c-4863af83cb39
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: cloudian
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cloudian
    spec:
      containers:
      - env:
        - name: CLOUDIAN
          value: https://10.81.1.55:19443
        - name: ENDPOINT_URL
          value: http://10.81.1.55:80/
        - name: USERTYPE
          value: User
        - name: LDAP
          value: "false"
        - name: ACTIVE
          value: "true"
        - name: USERNAME
          value: sysadmin
        - name: PASSWORD
          value: public
        - name: CLIENT_ADMIN
          value: client_admin
        - name: USERADMIN
          value: SystemAdmin
        - name: GROUPID
          value: "0"
        - name: USERSTATUS
          value: active
        - name: USERTYPES
          value: all
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: cloudian
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: cloudian
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8002"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: LOG_TARGET
          value: both
        - name: ENV_CHECK
          value: production
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/cloudian:23
        imagePullPolicy: IfNotPresent
        name: cloudian
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:09:39Z"
    lastUpdateTime: "2021-03-17T10:37:23Z"
    message: ReplicaSet "cloudian-5c87c8cb98" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:06Z"
    lastUpdateTime: "2021-03-25T13:34:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
