apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/cloudian cloudian=10.81.1.72:5000/cloudian:10
      --record=true
  creationTimestamp: "2021-01-14T05:57:38Z"
  generation: 10
  labels:
    io.kompose.service: cloudian
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"cloudian"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"CLOUDIAN"}:
                    .: {}
                    f:name: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8002,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:38Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"cloudian"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-20T13:25:03Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"cloudian"}:
                f:env:
                  k:{"name":"ACTIVE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CLIENT_ADMIN"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CLOUDIAN"}:
                    f:value: {}
                  k:{"name":"ENDPOINT_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"GROUPID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LDAP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERADMIN"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERTYPE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-02-12T12:42:30Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-12T12:42:35Z"
  name: cloudian
  namespace: default
  resourceVersion: "5737814"
  uid: 422b5609-65de-404b-9d28-5b3d494ea941
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: cloudian
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cloudian
    spec:
      containers:
      - env:
        - name: CLOUDIAN
          value: https://10.81.1.55:19443
        - name: ENDPOINT_URL
          value: http://10.81.1.55:80
        - name: USERTYPE
          value: User
        - name: LDAP
          value: "false"
        - name: ACTIVE
          value: "true"
        - name: USERNAME
          value: sysadmin
        - name: PASSWORD
          value: public
        - name: CLIENT_ADMIN
          value: client_admin
        - name: USERADMIN
          value: SystemAdmin
        - name: GROUPID
          value: "0"
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: cloudian
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: cloudian
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8002"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: LOG_TARGET
          value: both
        image: 10.81.1.72:5000/cloudian:10
        imagePullPolicy: IfNotPresent
        name: cloudian
        ports:
        - containerPort: 8002
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-21T06:46:26Z"
    lastUpdateTime: "2021-01-21T06:46:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-20T13:25:03Z"
    lastUpdateTime: "2021-02-12T12:42:35Z"
    message: ReplicaSet "cloudian-5d488f8ddb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
