apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-integration
  name: customer-integration
spec:
  replicas: 1
  selector:
      matchLabels:
          name: customer-integration
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: customer-integration
    spec:
      containers:
      - image: 10.81.1.50:5000/customer-integration:0.5
        name: customer-integration
        ports:
        - containerPort: 8003
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8020"
        - name: MONGODB_URI
          value: mongodb://mongodb-ip:27017/ms-customer-integration          
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1
