apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: customer-integration
  name: customer-integration
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: customer-integration
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: customer-integration
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8023"
        - name: MONGODB_URI
          value: mongodb://10.82.3.2:27017/ms-customer-integration
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/customer-integration:25
        imagePullPolicy: IfNotPresent
        name: customer-integration
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - containerPort: 8003
          protocol: TCP
