apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/hystax hystax=10.81.1.72:5000/hystax:16
      --record=true
  creationTimestamp: "2021-01-14T05:57:39Z"
  generation: 16
  labels:
    io.kompose.service: hystax
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"hystax"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"HYSTAX_EMAIL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"HYSTAX_IP"}:
                    .: {}
                    f:name: {}
                  k:{"name":"HYSTAX_PASSWORD"}:
                    .: {}
                    f:name: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_CUSTOMER_INTEGRATION"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MS_LOGGER_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PROTOCOL"}:
                    .: {}
                    f:name: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8015,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:39Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"hystax"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:19:37Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"hystax"}:
                f:env:
                  k:{"name":"ADMIN_ROLE_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ADMIN_ROLE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"HYSTAX_EMAIL"}:
                    f:value: {}
                  k:{"name":"HYSTAX_IP"}:
                    f:value: {}
                  k:{"name":"HYSTAX_PASSWORD"}:
                    f:value: {}
                  k:{"name":"MEMBER_ROLE_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MOUNTPOINT_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_CUSTOMER_INTEGRATION"}:
                    f:value: {}
                  k:{"name":"NODE_TLS_REJECT_UNAUTHORIZED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PARTNER_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PROTOCOL"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-02-12T14:23:29Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-12T14:23:33Z"
  name: hystax
  namespace: default
  resourceVersion: "5746128"
  uid: 44f73763-9fdc-4c53-9ccc-5a42aee41997
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: hystax
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: hystax
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8015"
        - name: PROTOCOL
          value: https
        - name: HYSTAX_IP
          value: 10.81.1.124
        - name: HYSTAX_EMAIL
          value: hasan.shafiq@ivolve.io
        - name: HYSTAX_PASSWORD
          value: 35e55f616cf716ae80cae4977c6389e9
        - name: MS_CUSTOMER_INTEGRATION
          value: customer-integration:8023
        - name: PARTNER_ID
          value: d7bd633c-4a9b-4607-908d-b2b25d524bc3
        - name: MOUNTPOINT_ID
          value: 59d5a6d8-ceb9-4870-b4ff-85d8ed1ae5b5
        - name: ADMIN_ROLE_ID
          value: "5"
        - name: MEMBER_ROLE_ID
          value: "6"
        - name: ADMIN_ROLE_NAME
          value: client_admin
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: middleware
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: middleware
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8001"
        - name: LOG_TARGET
          value: both
        image: 10.81.1.72:5000/hystax:16
        imagePullPolicy: IfNotPresent
        name: hystax
        ports:
        - containerPort: 8015
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-21T06:47:17Z"
    lastUpdateTime: "2021-01-21T06:47:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T06:19:37Z"
    lastUpdateTime: "2021-02-12T14:23:33Z"
    message: ReplicaSet "hystax-6dbfd6f6b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
