apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: hystax
  name: hystax
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hystax
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: hystax
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8015"
        - name: PROTOCOL
          value: https
        - name: HYSTAX_IP
          value: 10.81.1.124
        - name: ADMIN_ROLE_ID
          value: "5"
        - name: MEMBER_ROLE_ID
          value: "6"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: ADMIN_ROLE_NAME
          value: client_admin
        - name: HYSTAX_EMAIL
          value: hasan.shafiq@ivolve.io
        - name: MOUNTPOINT_ID
          value: e7d6a71f-f3f3-4f66-83d6-c851359f3a23
        - name: HYSTAX_PASSWORD
          value: 35e55f616cf716ae80cae4977c6389e9
        - name: MS_CUSTOMER_INTEGRATION
          value: http://customer-integration:8023
        - name: PRICING
          value: http://ms-settings:8005
        - name: MS_TRIALACCOUNT_URL
          value: http://trial-account:8020/trialAccount
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: middleware
        - name: PARTNER_ID
          value: d1e812c3-677c-4241-9093-fe8950547d46
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: middleware
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8001"
        - name: LOG_TARGET
          value: both
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/hystax:44
        imagePullPolicy: IfNotPresent
        name: hystax
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - containerPort: 8015
          protocol: TCP
