apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hystax
  name: hystax
spec:
  ports:
  - name: "8015"
    port: 8015
    targetPort: 8015
  selector:
    name: hystax
