apiVersion: v1
kind: Service
metadata:
  name: jboss-keycloak
  labels:
    name: jboss-keycloak
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
  selector:
    name: jboss-keycloak
