apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak
  managedFields:
  name: keycloak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: keycloak
    spec:
      containers:
      - env:
        - name: SERVER_URL
          value: http://qa-keycloak.ivlab.io:8080/auth/
        - name: DEFAULT_REALM_NAME
          value: DCM_REALM
        - name: CLIENT_ID
          value: PTCL
        - name: CLIENT_SECRET_KEY
          value: eddef4e6-571a-4a96-8411-6162b171f01b
        - name: CLIENT_ID_MARKETPLACE
          value: marketplace
        - name: CLIENT_SECRET_KEY_MARKETPLACE
          value: 861bf8e3-63e1-47f7-919a-dd059badf37d
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: keycloakusername
              name: secretenv
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: keycloakpassword
              name: secretenv
        - name: ADMIN_INITIAL_REALM
          value: master
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        - name: MONGODB_URI
          value: mongodb://10.82.3.2:27017
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: SECRET_KEY
          value: EqWl3xCW52Tpov4aUEbPDpa2ulMXZ0X2uK9HZyeEE5E=
        - name: TRIAL_ROLE
          value: CreateInstance
        image: 10.82.3.2:5000/keycloak:52
        imagePullPolicy: IfNotPresent
        name: keycloak
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /keycloak/health
            port: 8030
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - containerPort: 8030
          protocol: TCP
      hostAliases:    
      - hostnames:
        - qa.ivolve.io
        ip: 10.81.1.50
