apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kms
  managedFields:
  name: kms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kms
    spec:
      containers:
      - env:
        - name: PORT
          value: "8010"
        - name: BARBICAN_VESRION
          value: v1
        - name: BARBICAN_ENDPOINT
          value: http://cloud1.ivlab.io:9311
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: kms
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: kms
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8010"
        - name: LOG_TARGET
          value: both
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/kms:23
        imagePullPolicy: IfNotPresent
        name: kms
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8010
          protocol: TCP
