apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"28","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/marketplace-be marketplace-be=10.81.1.50:5000/marketplace-be:152 --record=true"},"creationTimestamp":"2021-02-10T08:27:58Z","generation":29,"labels":{"io.kompose.service":"marketplace-be"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"marketplace-be\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"ADMIN_PASSWORD\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ADMIN_USERNAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"API_KEY_INFRASTRUCTURE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"API_KEY_PRODUCT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"API_SECRET_INFRASTRUCTURE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"API_SECRET_PRODUCT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DB_LINK\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DEFAULT_NETWORK_CIDR\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"IAM\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"JEDDAH\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"JEDDAH_REGION_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"KILLBILL_PASS\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"KILLBILL_USER\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"KILL_BILL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MARKETPLACE_LINK\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MARKETPLACE_WEB_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MEMBER_ROLE_ID\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MIDDLEWARE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_EMAILER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_SMS_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ORG_PROJECT_ID\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTP_SECRET\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"RIYADH\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"RIYAD_REGION_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"STATIC_IV\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"TRIAL_ROLE\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":9100,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:hostAliases":{".":{},"k:{\"ip\":\"10.81.1.50\"}":{".":{},"f:hostnames":{},"f:ip":{}}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:26:33Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:26:43Z"}],"name":"marketplace-be","namespace":"default","resourceVersion":"27902033","selfLink":"/apis/apps/v1/namespaces/default/deployments/marketplace-be","uid":"c2447ad4-2e5e-478e-9117-b93b7fa6ced9"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"marketplace-be"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"marketplace-be"}},"spec":{"containers":[{"env":[{"name":"DB_LINK","value":"mongodb://10.81.1.50:27017/ms-marketplace-be"},{"name":"PORT","value":"9100"},{"name":"IAM","value":"iam:8003"},{"name":"MIDDLEWARE","value":"http://qa-middleware.ivolve.io:31907"},{"name":"MS_SMS_URL","value":"http://ms-sms:8013"},{"name":"MS_EMAILER_URL","value":"http://emailer:8009"},{"name":"KILL_BILL","value":"http://10.81.1.44:8080"},{"name":"API_KEY_PRODUCT","value":"L)~G8dm:t_h7h6y\u003c"},{"name":"API_SECRET_PRODUCT","value":"L)~G8dm:t_h7h6y\u003c"},{"name":"API_KEY_INFRASTRUCTURE","value":"X5#Y5UVm9`p$Vj^P"},{"name":"API_SECRET_INFRASTRUCTURE","value":"X5#Y5UVm9`p$Vj^P"},{"name":"KILLBILL_USER","value":"admin"},{"name":"KILLBILL_PASS","value":"password"},{"name":"OTP_SECRET","value":"Ahm3d!sWeaRingGr33n$h!rt"},{"name":"ADMIN_USERNAME","value":"marketplace_admin"},{"name":"ADMIN_PASSWORD","value":"noidEA%^\u0026981admin"},{"name":"MARKETPLACE_LINK","value":"http://qa-marketplace-fe.ivolve.io/"},{"name":"STATIC_IV","value":"c82ff58017e7dd2d4c82612ae4d43168"},{"name":"MARKETPLACE_WEB_IP","value":"http://qa-marketplace-fe.ivolve.io"},{"name":"MEMBER_ROLE_ID","value":"22da9d457933469cbb82fecaf7790fb0"},{"name":"ORG_PROJECT_ID","value":"f0858f7fcec04354bd5eb2108d05a7ae"},{"name":"DEFAULT_NETWORK_CIDR","value":"10.81.1.0/24"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"},{"name":"JEDDAH_REGION_NAME","value":"JEDDAH"},{"name":"RIYAD_REGION_NAME","value":"RIYADH"},{"name":"JEDDAH","value":"10.81.1.150"},{"name":"RIYADH","value":"10.81.1.155"},{"name":"TRIAL_ROLE","value":"CreateInstance"}],"image":"10.81.1.50:5000/marketplace-be:152","imagePullPolicy":"IfNotPresent","name":"marketplace-be","ports":[{"containerPort":9100,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","hostAliases":[{"hostnames":["qa.ivolve.io"],"ip":"10.81.1.50"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-02-17T09:14:19Z","lastUpdateTime":"2021-02-17T09:14:19Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-02-10T08:27:58Z","lastUpdateTime":"2021-03-03T11:26:43Z","message":"ReplicaSet \"marketplace-be-6694667876\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":29,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/marketplace-be marketplace-be=10.82.3.2:5000/marketplace-be:137
      --record=true
  creationTimestamp: "2021-03-15T07:09:03Z"
  generation: 8
  labels:
    io.kompose.service: marketplace-be
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"marketplace-be"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ADMIN_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ADMIN_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_KEY_INFRASTRUCTURE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_KEY_PRODUCT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_SECRET_INFRASTRUCTURE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_SECRET_PRODUCT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"DB_LINK"}:
                    .: {}
                    f:name: {}
                  k:{"name":"DEFAULT_NETWORK_CIDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IAM"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"JEDDAH"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"JEDDAH_REGION_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KILL_BILL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"KILLBILL_PASS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KILLBILL_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MARKETPLACE_LINK"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MARKETPLACE_WEB_IP"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MEMBER_ROLE_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MIDDLEWARE"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MS_EMAILER_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_SMS_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ORG_PROJECT_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OTP_SECRET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"RIYAD_REGION_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"RIYADH"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"STATIC_IV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"TRIAL_ROLE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":9100,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:hostAliases:
              .: {}
              k:{"ip":"10.81.1.50"}:
                .: {}
                f:hostnames: {}
                f:ip: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:03Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"marketplace-be"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:21:03Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"marketplace-be"}:
                f:env:
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
                  k:{"name":"DB_LINK"}:
                    f:value: {}
                  k:{"name":"KILL_BILL"}:
                    f:value: {}
                  k:{"name":"MARKETPLACE_LINK"}:
                    f:value: {}
                  k:{"name":"MARKETPLACE_WEB_IP"}:
                    f:value: {}
                  k:{"name":"MIDDLEWARE"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T10:40:56Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:02Z"
  name: marketplace-be
  namespace: default
  resourceVersion: "2197977"
  selfLink: /apis/apps/v1/namespaces/default/deployments/marketplace-be
  uid: ba4f988c-2a39-4a61-be4f-e7d8fdf05e34
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: marketplace-be
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: marketplace-be
    spec:
      containers:
      - env:
        - name: DB_LINK
          value: mongodb://10.82.3.2:27017/ms-marketplace-be
        - name: PORT
          value: "9100"
        - name: IAM
          value: iam:8003
        - name: MIDDLEWARE
          value: http://qa-middleware.ivlab.io:30779
        - name: MS_SMS_URL
          value: http://ms-sms:8013
        - name: MS_EMAILER_URL
          value: http://emailer:8009
        - name: KILL_BILL
          value: http://10.82.3.8:8080
        - name: API_KEY_PRODUCT
          value: L)~G8dm:t_h7h6y<
        - name: API_SECRET_PRODUCT
          value: L)~G8dm:t_h7h6y<
        - name: API_KEY_INFRASTRUCTURE
          value: X5#Y5UVm9`p$Vj^P
        - name: API_SECRET_INFRASTRUCTURE
          value: X5#Y5UVm9`p$Vj^P
        - name: KILLBILL_USER
          value: admin
        - name: KILLBILL_PASS
          value: password
        - name: OTP_SECRET
          value: Ahm3d!sWeaRingGr33n$h!rt
        - name: ADMIN_USERNAME
          value: marketplace_admin
        - name: ADMIN_PASSWORD
          value: noidEA%^&981admin
        - name: MARKETPLACE_LINK
          value: http://qa-marketplace-fe.ivlab.io/
        - name: STATIC_IV
          value: c82ff58017e7dd2d4c82612ae4d43168
        - name: MARKETPLACE_WEB_IP
          value: http://qa-marketplace-fe.ivlab.io
        - name: MEMBER_ROLE_ID
          value: 22da9d457933469cbb82fecaf7790fb0
        - name: ORG_PROJECT_ID
          value: f0858f7fcec04354bd5eb2108d05a7ae
        - name: DEFAULT_NETWORK_CIDR
          value: 10.81.1.0/24
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        - name: JEDDAH_REGION_NAME
          value: JEDDAH
        - name: RIYAD_REGION_NAME
          value: RIYADH
        - name: JEDDAH
          value: 10.81.1.150
        - name: RIYADH
          value: 10.81.1.155
        - name: TRIAL_ROLE
          value: CreateInstance
        image: 10.82.3.2:5000/marketplace-be:137
        imagePullPolicy: IfNotPresent
        name: marketplace-be
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9100
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - qa.ivolve.io
        ip: 10.81.1.50
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:21:03Z"
    lastUpdateTime: "2021-03-25T10:49:12Z"
    message: ReplicaSet "marketplace-be-6864484b4c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:02Z"
    lastUpdateTime: "2021-03-25T13:34:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
