apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: marketplace-fe
  name: marketplace-fe
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30628
  selector:
    name: marketplace-fe 
  type: NodePort
