apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: marketplace-be
  name: marketplace-be
spec:
  ports:
  - name: "9100"
    port: 9100
    targetPort: 9100
  selector:
    name: marketplace-be
