apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/marketplace-be marketplace-be=10.81.1.72:5000/marketplace-be:19
      --record=true
  creationTimestamp: "2021-01-14T05:57:42Z"
  generation: 16
  labels:
    io.kompose.service: marketplace-be
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"marketplace-be"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ADMIN_PASSWORD"}:
                    .: {}
                    f:name: {}
                  k:{"name":"ADMIN_USERNAME"}:
                    .: {}
                    f:name: {}
                  k:{"name":"API_KEY_INFRASTRUCTURE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_KEY_PRODUCT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_SECRET_INFRASTRUCTURE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"API_SECRET_PRODUCT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_LINK"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IAM"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KILL_BILL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KILLBILL_PASS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KILLBILL_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MIDDLEWARE"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MS_EMAILER_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OTP_SECRET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"STATIC_IV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":9100,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:42Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"marketplace-be"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:18:05Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"marketplace-be"}:
                f:env:
                  k:{"name":"ADMIN_PASSWORD"}:
                    f:value: {}
                  k:{"name":"ADMIN_USERNAME"}:
                    f:value: {}
                  k:{"name":"MIDDLEWARE"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-02-15T08:23:05Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-15T08:23:10Z"
  name: marketplace-be
  namespace: default
  resourceVersion: "6067262"
  uid: ee26303b-c381-4568-9921-5bddf7db1fe8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: marketplace-be
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: marketplace-be
    spec:
      containers:
      - env:
        - name: DB_LINK
          value: mongodb://10.81.1.72:27017/ms-marketplace-be
        - name: PORT
          value: "9100"
        - name: IAM
          value: iam:8003
        - name: MIDDLEWARE
          value: http://dev-marketplace-be.ivolve.io:30667
        - name: MS_EMAILER_URL
          value: http://emailer:8009
        - name: KILL_BILL
          value: http://10.81.1.59:8080
        - name: API_KEY_PRODUCT
          value: L)~G8dm:t_h7h6y<
        - name: API_SECRET_PRODUCT
          value: L)~G8dm:t_h7h6y<
        - name: API_KEY_INFRASTRUCTURE
          value: X5#Y5UVm9`p$Vj^P
        - name: API_SECRET_INFRASTRUCTURE
          value: X5#Y5UVm9`p$Vj^P
        - name: KILLBILL_USER
          value: admin
        - name: KILLBILL_PASS
          value: password
        - name: OTP_SECRET
          value: Ahm3d!sWeaRingGr33n$h!rt
        - name: ADMIN_USERNAME
          value: ahmed.hasan
        - name: ADMIN_PASSWORD
          value: theweekndXO
        - name: STATIC_IV
          value: c82ff58017e7dd2d4c82612ae4d43168
        image: 10.81.1.72:5000/marketplace-be:19
        imagePullPolicy: IfNotPresent
        name: marketplace-be
        ports:
        - containerPort: 9100
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-21T06:46:21Z"
    lastUpdateTime: "2021-01-21T06:46:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T06:18:05Z"
    lastUpdateTime: "2021-02-15T08:23:10Z"
    message: ReplicaSet "marketplace-be-d7d5b498b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
