apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: marketplace-be
  name: marketplace-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: marketplace-be
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: marketplace-be
    spec:
      containers:
      - env:
        - name: DB_LINK
          value: mongodb://10.82.3.2:27017/ms-marketplace-demo
        - name: PORT
          value: "9100"
        - name: IAM
          value: iam:8003
        - name: MIDDLEWARE
          value: http://qa-middleware.ivlab.io:30779
        - name: MS_SMS_URL
          value: http://ms-sms:8013
        - name: MS_EMAILER_URL
          value: http://emailer:8009
        - name: KILL_BILL
          value: http://10.82.3.8:8080
        - name: API_KEY_PRODUCT
          value: L)~G8dm:t_h7h6y<
        - name: API_SECRET_PRODUCT
          value: L)~G8dm:t_h7h6y<
        - name: API_KEY_INFRASTRUCTURE
          value: X5#Y5UVm9`p$Vj^P
        - name: API_SECRET_INFRASTRUCTURE
          value: X5#Y5UVm9`p$Vj^P
        - name: KILLBILL_USER
          valueFrom:
            secretKeyRef:
              key: killbilluser 
              name: secretenv        
        - name: KILLBILL_PASS
          valueFrom:
            secretKeyRef:
              key: killbillpass
              name: secretenv
        - name: OTP_SECRET
          value: Ahm3d!sWeaRingGr33n$h!rt
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: killbilladminuser
              name: secretenv
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: killbilladminpass
              name: secretenv
        - name: MARKETPLACE_LINK
          value: http://qa-marketplace-fe.ivlab.io/
        - name: STATIC_IV
          value: c82ff58017e7dd2d4c82612ae4d43168
        - name: MARKETPLACE_WEB_IP
          value: http://qa-marketplace-fe.ivlab.io
        - name: MEMBER_ROLE_ID
          value: 22da9d457933469cbb82fecaf7790fb0
        - name: ORG_PROJECT_ID
          value: f0858f7fcec04354bd5eb2108d05a7ae
        - name: DEFAULT_NETWORK_CIDR
          value: 10.81.1.0/24
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        - name: JEDDAH_REGION_NAME
          value: JEDDAH
        - name: RIYAD_REGION_NAME
          value: RIYADH
        - name: JEDDAH
          value: 10.81.1.150
        - name: RIYADH
          value: 10.81.1.155
        - name: TRIAL_ROLE
          value: CreateInstance
        image: 10.82.3.2:5000/marketplace-be:140
        imagePullPolicy: IfNotPresent
        name: marketplace-be
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9100
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9100
          protocol: TCP
      hostAliases:
      - hostnames:
        - qa.ivolve.io
        ip: 10.81.1.50
