apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/middleware middleware=10.81.1.72:5000/middleware:17
      --record=true
  creationTimestamp: "2021-01-14T05:57:43Z"
  generation: 16
  labels:
    io.kompose.service: middleware
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"middleware"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"BILLING_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CLOUDIAN_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CUSTOMER_INTEGRATION_BASEURL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"EGRESS_REPORTING_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"EMAILER_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"HYSTAX_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IAM"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KEYCLOAK_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KMS_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_CUSTOMER_CONTRACTS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_MARKETPLACE_BE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_SETTINGS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_TRIALACCOUNT_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ORCHESTRATOR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"RESERVE_ECS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"TENANT_QUOTA_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USAGE_REPORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8001,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:43Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"middleware"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:19:46Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"middleware"}:
                f:env:
                  k:{"name":"CUSTOMER_INTEGRATION_BASEURL"}:
                    f:value: {}
                  k:{"name":"DBVM_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DCMTOSAP_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"HANA_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_MIDDLEWARE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PROVIDERS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-02-12T14:36:34Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-12T14:36:38Z"
  name: middleware
  namespace: default
  resourceVersion: "5747237"
  uid: a99df407-71e6-4aac-ac46-18d7b0039281
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: middleware
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: middleware
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: IAM
          value: http://iam:8003
        - name: ORCHESTRATOR
          value: http://python-app:8002
        - name: USAGE_REPORT
          value: http://usage-report:8006
        - name: EMAILER_BASEURL
          value: http://emailer:8009
        - name: TENANT_QUOTA_BASEURL
          value: http://project-quotas:8018/tenant/quotas
        - name: HYSTAX_BASEURL
          value: http://hystax:8015
        - name: CUSTOMER_INTEGRATION_BASEURL
          value: http://customer-integration:8023
        - name: EGRESS_REPORTING_URL
          value: http://ntopng-client:8669/egressReporting/
        - name: PORT
          value: "8001"
        - name: KMS_BASEURL
          value: http://kms:8010
        - name: RESERVE_ECS
          value: http://reserved-ecs:8011
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: middleware
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: middleware
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8001"
        - name: LOG_TARGET
          value: both
        - name: MS_SETTINGS
          value: http://ms-settings:8005
        - name: MS_TRIALACCOUNT_URL
          value: http://trial-account:8020/trialAccount
        - name: BILLING_URL
          value: http://ms-billing:8022
        - name: MS_CUSTOMER_CONTRACTS
          value: http://customer-contract:8024
        - name: CLOUDIAN_BASEURL
          value: http://cloudian:8021
        - name: KEYCLOAK_BASEURL
          value: http://keycloak:8030/keycloak
        - name: MS_MARKETPLACE_BE
          value: http://marketplace-be:9100
        - name: HANA_BASEURL
          value: http://database:8029
        - name: MS_MIDDLEWARE
          value: http://middleware:8001
        - name: DBVM_BASEURL
          value: http://database:8029
        - name: DCMTOSAP_BASEURL
          value: http://dcmtosap:8031
        - name: PROVIDERS
          value: cloudian,hystax
        image: 10.81.1.72:5000/middleware:17
        imagePullPolicy: IfNotPresent
        name: middleware
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-29T07:53:26Z"
    lastUpdateTime: "2021-01-29T07:53:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T06:19:46Z"
    lastUpdateTime: "2021-02-12T14:36:38Z"
    message: ReplicaSet "middleware-548987fd9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
