apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: monitoring
  name: monitoring
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: monitoring
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8800"
        - name: PROTOCOL
          value: http
        - name: MONASCA_IP
          value: 10.81.1.46:8070
        - name: MIDDLEWARE_IP
          value: http://middleware:8001
        - name: IAM_IP
          value: http://iam:8003
        - name: MONASCA_CPU_TIME
          value: 50,seconds
        - name: MONASCA_RAM_TIME
          value: 6.5,days
        - name: MONASCA_NETWORK_DOWN_TIME
          value: 6,minutes
        - name: MONASCA_NETWORK_UP_TIME
          value: 6,minutes
        - name: MONASCA_STORAGE_TIME
          value: 0,seconds
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: monitoring
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: monitoring
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8800"
        - name: LOG_TARGET
          value: both
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: development
        image: 10.82.3.2:5000/monitoring:26
        imagePullPolicy: IfNotPresent
        name: monitoring
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8800
          protocol: TCP
