apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/monitoring monitoring=10.81.1.72:5000/monitoring:8
      --record=true
  creationTimestamp: "2021-01-14T05:57:38Z"
  generation: 5
  labels:
    io.kompose.service: monitoring
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"monitoring"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"IAM_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MIDDLEWARE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONASCA_CPU_TIME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONASCA_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONASCA_NETWORK_DOWN_TIME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONASCA_NETWORK_UP_TIME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONASCA_RAM_TIME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONASCA_STORAGE_TIME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PROTOCOL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8800,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:38Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"monitoring"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:21:45Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-03T15:36:20Z"
  name: monitoring
  namespace: default
  resourceVersion: "4699723"
  uid: 1c73959f-2071-497c-9e76-3315c773c813
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: monitoring
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8800"
        - name: PROTOCOL
          value: http
        - name: MONASCA_IP
          value: 10.81.1.60:8070
        - name: MIDDLEWARE_IP
          value: http://middleware:8001
        - name: IAM_IP
          value: http://iam:8003
        - name: MONASCA_CPU_TIME
          value: 50,seconds
        - name: MONASCA_RAM_TIME
          value: 6.5,days
        - name: MONASCA_NETWORK_DOWN_TIME
          value: 6,minutes
        - name: MONASCA_NETWORK_UP_TIME
          value: 6,minutes
        - name: MONASCA_STORAGE_TIME
          value: 0,seconds
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: monitoring
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: monitoring
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8800"
        - name: LOG_TARGET
          value: both
        image: 10.81.1.72:5000/monitoring:8
        imagePullPolicy: IfNotPresent
        name: monitoring
        ports:
        - containerPort: 8800
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-21T06:45:49Z"
    lastUpdateTime: "2021-01-21T06:45:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T06:21:45Z"
    lastUpdateTime: "2021-02-03T15:36:21Z"
    message: ReplicaSet "monitoring-65fb57cc9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
