apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ms-billing
  name: ms-billing
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ms-billing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ms-billing
    spec:
      containers:
      - env:
        - name: PORT
          value: "8022"
        - name: NODE_ENV
          value: development
        - name: BILLING_URL
          value: mongodb://10.82.3.2:27017/ms-billing
        - name: KILLBILL_ENDPOINT
          value: http://10.82.3.8:8080
        - name: KILLBILL_ADMIN_CREDENTIAL
          value: YWRtaW46cGFzc3dvcmQ=
        - name: KILLBILL_API_SECRET
          value: andrews
        - name: KILLBILL_GLOBAL_KEY
          value: global_APIKEY
        - name: KILLBILL_REPLACEMENT_DB
          value: mongodb://10.82.3.2:27017/killbill_replacement
        - name: MS_KILLBILL_LISTENER
          value: http://10.82.3.2:8024
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: ms-billing
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: ms-billing
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8020"
        - name: LOG_TARGET
          value: both
        - name: ELASTIC_IP_PRICE
          value: "80"
        - name: APM_SERVER_URL
          value: http://10.82.3.29:8201
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/ms-billing:23
        imagePullPolicy: IfNotPresent
        name: ms-billing
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8020
          protocol: TCP
