apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"11","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/ms-logger ms-logger=10.81.1.50:5000/ms-logger:17 --record=true"},"creationTimestamp":"2020-10-19T13:16:46Z","generation":11,"labels":{"io.kompose.service":"ms-logger"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"ms-logger\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOGSTASH_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOGSTASH_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOG_TARGET\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_SECRET_KEY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"SECRET_KEY\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8011,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:30:35Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:30:43Z"}],"name":"ms-logger","namespace":"default","resourceVersion":"27902680","selfLink":"/apis/apps/v1/namespaces/default/deployments/ms-logger","uid":"da1c41fd-967d-4907-95ba-04b15dfbd904"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"ms-logger"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"ms-logger"}},"spec":{"containers":[{"env":[{"name":"MS_LOGGER_PORT","value":"8012"},{"name":"MS_LOGGER_SECRET_KEY","value":"BC2B36B89F3B83ADCAD56"},{"name":"MS_LOGGER_THIS_SERVICE_NAME","value":"ms-logger"},{"name":"MS_LOGGER_THIS_SERVICE_IP","value":"ms-logger"},{"name":"MS_LOGGER_THIS_SERVICE_PORT","value":"8012"},{"name":"LOG_TARGET","value":"both"},{"name":"LOGSTASH_IP","value":"10.81.1.85"},{"name":"LOGSTASH_PORT","value":"5000"},{"name":"SECRET_KEY","value":"BC2B36B89F3B83ADCAD56"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"}],"image":"10.81.1.50:5000/ms-logger:17","imagePullPolicy":"IfNotPresent","name":"ms-logger","ports":[{"containerPort":8011,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-12-18T11:46:35Z","lastUpdateTime":"2020-12-18T11:46:35Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-10-19T14:04:09Z","lastUpdateTime":"2021-03-03T11:30:43Z","message":"ReplicaSet \"ms-logger-59c5b4d7bf\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":11,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/ms-logger ms-logger=10.82.3.2:5000/ms-logger:18
      --record=true
  creationTimestamp: "2021-03-15T07:09:04Z"
  generation: 3
  labels:
    io.kompose.service: ms-logger
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"ms-logger"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOGSTASH_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOGSTASH_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8011,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:04Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"ms-logger"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:22:17Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"ms-logger"}:
                f:env:
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T10:42:41Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:01Z"
  name: ms-logger
  namespace: default
  resourceVersion: "2197953"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ms-logger
  uid: f0f50d66-6923-437b-8f16-c5c90589829e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ms-logger
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ms-logger
    spec:
      containers:
      - env:
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B89F3B83ADCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: ms-logger
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: ms-logger
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8012"
        - name: LOG_TARGET
          value: both
        - name: LOGSTASH_IP
          value: 10.81.1.85
        - name: LOGSTASH_PORT
          value: "5000"
        - name: SECRET_KEY
          value: BC2B36B89F3B83ADCAD56
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/ms-logger:18
        imagePullPolicy: IfNotPresent
        name: ms-logger
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8011
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:22:17Z"
    lastUpdateTime: "2021-03-17T10:42:43Z"
    message: ReplicaSet "ms-logger-f7d58547b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:01Z"
    lastUpdateTime: "2021-03-25T13:34:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
