apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ms-logger
  name: ms-logger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ms-logger
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ms-logger
    spec:
      containers:
      - env:
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B89F3B83ADCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: ms-logger
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: ms-logger
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8012"
        - name: LOG_TARGET
          value: both
        - name: LOGSTASH_IP
          value: 10.81.1.85
        - name: LOGSTASH_PORT
          value: "5000"
        - name: SECRET_KEY
          value: BC2B36B89F3B83ADCAD56
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.28:5001/ms-logger:4
        imagePullPolicy: IfNotPresent
        name: ms-logger
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8011
          protocol: TCP
