apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-settings
  name: ms-settings
spec:
  ports:
  - name: "8005"
    port: 8005
    targetPort: 8005
  selector:
    name: ms-settings
