apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-util-helpers
  name: ms-util-helpers
spec:
  ports:
  - name: "8014"
    port: 8014
    targetPort: 8014
  selector:
    name: ms-util-helpers
