apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"11","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/ntopng-client ntopng-client=10.81.1.50:5000/ntopng-client:22 --record=true"},"creationTimestamp":"2020-10-19T13:16:52Z","generation":11,"labels":{"io.kompose.service":"ntopng-client"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"ntopng-client\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NODE_ENV\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NOVA_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NOVA_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NTOPNG_BASE_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NTOPNG_PASSWORD\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NTOPNG_USERNAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NTOP_INTERFACE_ID\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"usageReport_mongoDB_URI\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8669,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:32:11Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:32:19Z"}],"name":"ntopng-client","namespace":"default","resourceVersion":"27902988","selfLink":"/apis/apps/v1/namespaces/default/deployments/ntopng-client","uid":"576bd9e1-da37-45a0-b1a2-44d7caabd790"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"ntopng-client"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"ntopng-client"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"development"},{"name":"NOVA_URL","value":"http://cloud2.ivlab.io"},{"name":"NOVA_PORT","value":"8774"},{"name":"PORT","value":"8669"},{"name":"NTOPNG_BASE_URL","value":"http://10.131.129.196:3000"},{"name":"NTOPNG_USERNAME","value":"admin"},{"name":"NTOPNG_PASSWORD","value":"letmein"},{"name":"NTOP_INTERFACE_ID","value":"3"},{"name":"usageReport_mongoDB_URI","value":"mongodb://10.81.1.50:27017"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"}],"image":"10.81.1.50:5000/ntopng-client:22","imagePullPolicy":"IfNotPresent","name":"ntopng-client","ports":[{"containerPort":8669,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-02-18T11:24:28Z","lastUpdateTime":"2021-02-18T11:24:28Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-01-14T08:57:03Z","lastUpdateTime":"2021-03-03T11:32:19Z","message":"ReplicaSet \"ntopng-client-7ddf97566c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":11,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/ntopng-client ntopng-client=10.82.3.2:5000/ntopng-client:24
      --record=true
  creationTimestamp: "2021-03-15T07:09:04Z"
  generation: 5
  labels:
    io.kompose.service: ntopng-client
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"ntopng-client"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NOVA_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NOVA_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"NTOP_INTERFACE_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NTOPNG_BASE_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NTOPNG_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NTOPNG_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"usageReport_mongoDB_URI"}:
                    .: {}
                    f:name: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8669,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:04Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"ntopng-client"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:23:00Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"ntopng-client"}:
                f:env:
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
                  k:{"name":"NOVA_URL"}:
                    f:value: {}
                  k:{"name":"usageReport_mongoDB_URI"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T12:50:25Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T14:44:36Z"
  name: ntopng-client
  namespace: default
  resourceVersion: "2208985"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ntopng-client
  uid: 5246b8aa-d793-4846-9ab9-a5d6c653f56e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ntopng-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ntopng-client
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: NOVA_URL
          value: http://cloud1.ivlab.io
        - name: NOVA_PORT
          value: "8774"
        - name: PORT
          value: "8669"
        - name: NTOPNG_BASE_URL
          value: http://10.131.129.196:3000
        - name: NTOPNG_USERNAME
          value: admin
        - name: NTOPNG_PASSWORD
          value: letmein
        - name: NTOP_INTERFACE_ID
          value: "3"
        - name: usageReport_mongoDB_URI
          value: mongodb://10.82.3.2:27017
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/ntopng-client:24
        imagePullPolicy: IfNotPresent
        name: ntopng-client
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8669
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:23:00Z"
    lastUpdateTime: "2021-03-17T12:50:27Z"
    message: ReplicaSet "ntopng-client-76874ff78d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T14:44:36Z"
    lastUpdateTime: "2021-03-25T14:44:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
