apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ntopng-client
  name: ntopng-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ntopng-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ntopng-client
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: NOVA_URL
          value: http://cloud1.ivlab.io
        - name: NOVA_PORT
          value: "8774"
        - name: PORT
          value: "8669"
        - name: NTOPNG_BASE_URL
          value: http://10.131.129.196:3000
        - name: NTOPNG_USERNAME
          value: admin
        - name: NTOPNG_PASSWORD
          value: letmein
        - name: NTOP_INTERFACE_ID
          value: "3"
        - name: usageReport_mongoDB_URI
          value: mongodb://10.82.3.2:27017
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/ntopng-client:27
        imagePullPolicy: IfNotPresent
        name: ntopng-client
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8669
          protocol: TCP
