apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/ntopng-client ntopng-client=10.81.1.72:5000/ntopng-client:13
      --record=true
  creationTimestamp: "2021-01-14T05:57:46Z"
  generation: 10
  labels:
    io.kompose.service: ntopng-client
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"ntopng-client"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NOVA_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NOVA_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NTOPNG_BASE_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NTOPNG_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NTOPNG_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8669,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:46Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"ntopng-client"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:21:20Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-03T15:36:11Z"
  name: ntopng-client
  namespace: default
  resourceVersion: "4699688"
  uid: dedf6621-5ce9-4ba1-bb75-f6b4e5c8bb5e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ntopng-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ntopng-client
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: NOVA_URL
          value: http://10.81.1.100
        - name: NOVA_PORT
          value: "8774"
        - name: PORT
          value: "8669"
        - name: NTOPNG_BASE_URL
          value: http://:3000
        - name: NTOPNG_USERNAME
          value: admin
        - name: NTOPNG_PASSWORD
          value: letmein
        image: 10.81.1.72:5000/ntopng-client:13
        imagePullPolicy: IfNotPresent
        name: ntopng-client
        ports:
        - containerPort: 8669
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-21T06:45:41Z"
    lastUpdateTime: "2021-01-21T06:45:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T06:21:20Z"
    lastUpdateTime: "2021-02-03T15:36:11Z"
    message: ReplicaSet "ntopng-client-7475f7c666" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
