apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: reserved-ecs
  managedFields:
  name: reserved-ecs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reserved-ecs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: reserved-ecs
    spec:
      containers:
      - env:
        - name: PORT
          value: "8011"
        - name: MONGODB_URI
          value: mongodb://10.82.3.2:27017/ms-reserve-ecs
        - name: ORCHESTRATOR
          value: python-app:8002
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: reserved-ecs
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: reserved-ecs
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8011"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: LOG_TARGET
          value: both
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/reserved-ecs:27
        imagePullPolicy: IfNotPresent
        name: reserved-ecs
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8011
          protocol: TCP
