apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: reserved-ecs
  name: reserved-ecs
spec:
  replicas: 1
  selector:
      matchLabels:
          name: reserved-ecs
  template:
    metadata:
      creationTimestamp: null
      labels:
              #io.kompose.service: reserved-ecs
        name: reserved-ecs
    spec:
      containers:
      - image: 192.168.1.182:5000/reserved-ecs:0.5
        name: reserved-ecs
        ports:
        - containerPort: 8011
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8011"
        - name: MONGODB_URI
          value: mongodb://mongobd-ip:27017/ms-reserve-ecs
        - name: ORCHESTRATOR
          value: python-app:8002
          #ms-logger serice
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: reserved-ecs
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: reserved-ecs
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8011"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: LOG_TARGET
          value: both
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1
