apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"19","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/reserved-ecs reserved-ecs=10.81.1.50:5000/reserved-ecs:23 --record=true"},"creationTimestamp":"2020-10-19T13:17:06Z","generation":20,"labels":{"io.kompose.service":"reserved-ecs"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"reserved-ecs\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOG_TARGET\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_URI\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_SECRET_KEY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ORCHESTRATOR\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PORT\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8011,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:34:44Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:34:55Z"}],"name":"reserved-ecs","namespace":"default","resourceVersion":"27903528","selfLink":"/apis/apps/v1/namespaces/default/deployments/reserved-ecs","uid":"4510c60a-936a-40b2-970a-416619e1cb64"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"reserved-ecs"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"reserved-ecs"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"8011"},{"name":"MONGODB_URI","value":"mongodb://10.81.1.50:27017/ms-reserve-ecs"},{"name":"ORCHESTRATOR","value":"python-app:8002"},{"name":"MS_LOGGER_THIS_SERVICE_NAME","value":"reserved-ecs"},{"name":"MS_LOGGER_THIS_SERVICE_IP","value":"reserved-ecs"},{"name":"MS_LOGGER_THIS_SERVICE_PORT","value":"8011"},{"name":"MS_LOGGER_IP","value":"ms-logger"},{"name":"MS_LOGGER_PORT","value":"8012"},{"name":"MS_LOGGER_SECRET_KEY","value":"BC2B36B81AB89F3B83AD227DCAD56"},{"name":"LOG_TARGET","value":"both"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"}],"image":"10.81.1.50:5000/reserved-ecs:23","imagePullPolicy":"IfNotPresent","name":"reserved-ecs","ports":[{"containerPort":8011,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-01-15T06:34:15Z","lastUpdateTime":"2021-01-15T06:34:15Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-02-08T08:25:52Z","lastUpdateTime":"2021-03-03T11:34:55Z","message":"ReplicaSet \"reserved-ecs-7d445c9c49\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":20,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/reserved-ecs reserved-ecs=10.82.3.2:5000/reserved-ecs:24
      --record=true
  creationTimestamp: "2021-03-15T07:09:04Z"
  generation: 4
  labels:
    io.kompose.service: reserved-ecs
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"reserved-ecs"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_URI"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MS_LOGGER_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ORCHESTRATOR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8011,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:04Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"reserved-ecs"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:23:38Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"reserved-ecs"}:
                f:env:
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
                  k:{"name":"MONGODB_URI"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T10:45:25Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:05Z"
  name: reserved-ecs
  namespace: default
  resourceVersion: "2198089"
  selfLink: /apis/apps/v1/namespaces/default/deployments/reserved-ecs
  uid: 52ab1b3b-e4f9-4cf2-9cb8-50e096e54ee0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: reserved-ecs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: reserved-ecs
    spec:
      containers:
      - env:
        - name: PORT
          value: "8011"
        - name: MONGODB_URI
          value: mongodb://10.82.3.2:27017/ms-reserve-ecs
        - name: ORCHESTRATOR
          value: python-app:8002
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: reserved-ecs
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: reserved-ecs
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8011"
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: LOG_TARGET
          value: both
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/reserved-ecs:24
        imagePullPolicy: IfNotPresent
        name: reserved-ecs
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8011
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:23:38Z"
    lastUpdateTime: "2021-03-17T10:45:27Z"
    message: ReplicaSet "reserved-ecs-67b786795b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:05Z"
    lastUpdateTime: "2021-03-25T13:34:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
