apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: sms
    spec:
      containers:
      - env:
        - name: PORT
          value: "8013"
        - name: SMPP_SEND_ENDPOINT
          value: https://mshastra.com/sendsms_api_json.aspx
        - name: SMPP_USER_ID
          value: "20097735"
        - name: SMPP_SENDER_ID
          value: MOBSMS
        - name: SMPP_LANGUAGE
          value: English
        - name: SMPP_PASSWORD
          value: 39cfdd386e260e2e35dd8a3fdabc8921
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/sms:9
        imagePullPolicy: IfNotPresent
        name: sms
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8013
          protocol: TCP
