apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"29","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/trial-account trial-account=10.81.1.50:5000/trial-account:29 --record=true"},"creationTimestamp":"2020-12-17T08:11:31Z","generation":29,"labels":{"io.kompose.service":"trial-account"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"trial-account\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"ADMINUSERNAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ADMINUSERPASSWORD\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ADMINUSERPROJECT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ALLOWED_ORIGIN_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"CLOUDIAN_BASEURL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"COMPUTE_API_VERSION\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"COMPUTE_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DCM_MARKETPLACE_ACTIVATION\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"KEYCLOAK_BASEURL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MIDDLEWARE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONGODB_BASE_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"NODE_ENV\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OPENSTACK_KEYSTONE_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OPENSTACK_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ORCHESTRATOR\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"SCHEDULING_MAIL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"SENDER_PASSWORD\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"SENDER_USERNAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"SMTP_HOST\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8020,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:35:39Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:35:49Z"}],"name":"trial-account","namespace":"default","resourceVersion":"27903741","selfLink":"/apis/apps/v1/namespaces/default/deployments/trial-account","uid":"b00d9aaa-6c5d-4a58-81e1-379c3ed5815a"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"trial-account"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"trial-account"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"development"},{"name":"ALLOWED_ORIGIN_IP","value":"10.81.1.50"},{"name":"OPENSTACK_KEYSTONE_URL","value":"http://10.81.1.150:5000"},{"name":"PORT","value":"8020"},{"name":"MONGODB_BASE_URL","value":"mongodb://10.81.1.50:27017/ms-trialAccount"},{"name":"SENDER_USERNAME","value":"testingmailivolve@yahoo.com"},{"name":"SENDER_PASSWORD","value":"password"},{"name":"SMTP_HOST","value":"smtp.mail.yahoo.com"},{"name":"SCHEDULING_MAIL","value":"* * */2 * *"},{"name":"ORCHESTRATOR","value":"http://python-app:8002"},{"name":"ADMINUSERNAME","value":"17bd2447248063f35bb76aa66dc557ed"},{"name":"ADMINUSERPASSWORD","value":"6d828ac75855691962cbdfc98e35945e"},{"name":"ADMINUSERPROJECT","value":"36724e0e9df207ac65d9b0e6d984b71abbe2f0a13c4660d8dbbf4b2f191c74417946fb7013fee7c95910a823f641fa65"},{"name":"DCM_MARKETPLACE_ACTIVATION","value":"http://dcm-marketplace:8033"},{"name":"MIDDLEWARE","value":"http://middleware:8001"},{"name":"KEYCLOAK_BASEURL","value":"http://10.81.1.50:32354/keycloak"},{"name":"CLOUDIAN_BASEURL","value":"http://cloudian:8021"},{"name":"OPENSTACK_URL","value":"http://cloud2.ivlab.io"},{"name":"COMPUTE_PORT","value":"8774"},{"name":"COMPUTE_API_VERSION","value":"v2"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"}],"image":"10.81.1.50:5000/trial-account:29","imagePullPolicy":"IfNotPresent","name":"trial-account","ports":[{"containerPort":8020,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-03-01T07:38:21Z","lastUpdateTime":"2021-03-01T07:38:21Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-12-31T12:06:53Z","lastUpdateTime":"2021-03-03T11:35:49Z","message":"ReplicaSet \"trial-account-6db5f5b54f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":29,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/trial-account trial-account=10.82.3.2:5000/trial-account:29
      --record=true
  creationTimestamp: "2021-03-15T07:09:04Z"
  generation: 5
  labels:
    io.kompose.service: trial-account
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"trial-account"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ADMINUSERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ADMINUSERPASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ADMINUSERPROJECT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ALLOWED_ORIGIN_IP"}:
                    .: {}
                    f:name: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"CLOUDIAN_BASEURL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"COMPUTE_API_VERSION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"COMPUTE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DCM_MARKETPLACE_ACTIVATION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KEYCLOAK_BASEURL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MIDDLEWARE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONGODB_BASE_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OPENSTACK_KEYSTONE_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"OPENSTACK_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"ORCHESTRATOR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SCHEDULING_MAIL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SENDER_PASSWORD"}:
                    .: {}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
                    f:name: {}
                    f:value: {}
                  k:{"name":"SENDER_USERNAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SMTP_HOST"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8020,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:04Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"trial-account"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:23:51Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"trial-account"}:
                f:env:
                  k:{"name":"ALLOWED_ORIGIN_IP"}:
                    f:value: {}
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
                  k:{"name":"KEYCLOAK_BASEURL"}:
                    f:value: {}
                  k:{"name":"MONGODB_BASE_URL"}:
                    f:value: {}
                  k:{"name":"OPENSTACK_KEYSTONE_URL"}:
                    f:value: {}
                  k:{"name":"OPENSTACK_URL"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T12:53:57Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:02Z"
  name: trial-account
  namespace: default
  resourceVersion: "2197967"
  selfLink: /apis/apps/v1/namespaces/default/deployments/trial-account
  uid: be9dae34-3046-44ee-b175-2705f095ca80
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: trial-account
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: trial-account
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: ALLOWED_ORIGIN_IP
          value: 10.82.3.2
        - name: OPENSTACK_KEYSTONE_URL
          value: http://cloud1.ivlab.io:5000
        - name: PORT
          value: "8020"
        - name: MONGODB_BASE_URL
          value: mongodb://10.82.3.2:27017/ms-trialAccount
        - name: SENDER_USERNAME
          value: testingmailivolve@yahoo.com
        - name: SENDER_PASSWORD
          value: password
        - name: SMTP_HOST
          value: smtp.mail.yahoo.com
        - name: SCHEDULING_MAIL
          value: '* * */2 * *'
        - name: ORCHESTRATOR
          value: http://python-app:8002
        - name: ADMINUSERNAME
          value: 17bd2447248063f35bb76aa66dc557ed
        - name: ADMINUSERPASSWORD
          value: 6d828ac75855691962cbdfc98e35945e
        - name: ADMINUSERPROJECT
          value: 36724e0e9df207ac65d9b0e6d984b71abbe2f0a13c4660d8dbbf4b2f191c74417946fb7013fee7c95910a823f641fa65
        - name: DCM_MARKETPLACE_ACTIVATION
          value: http://dcm-marketplace:8033
        - name: MIDDLEWARE
          value: http://middleware:8001
        - name: KEYCLOAK_BASEURL
          value: http://10.82.3.6:32354/keycloak
        - name: CLOUDIAN_BASEURL
          value: http://cloudian:8021
        - name: OPENSTACK_URL
          value: http://cloud1.ivlab.io
        - name: COMPUTE_PORT
          value: "8774"
        - name: COMPUTE_API_VERSION
          value: v2
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/trial-account:29
        imagePullPolicy: IfNotPresent
        name: trial-account
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8020
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:23:51Z"
    lastUpdateTime: "2021-03-17T12:53:59Z"
    message: ReplicaSet "trial-account-6d9cc68ccc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:02Z"
    lastUpdateTime: "2021-03-25T13:34:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
