apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: usage-report
  name: usage-report
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: usage-report
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: usage-report
    spec:
      containers:
      - env:
        - name: PORT
          value: "8006"
        - name: DB_LINK
          value: mongodb://10.82.3.2:27017
        - name: OPENSTACK_URL
          value: http://cloud1.ivlab.io
        - name: KEYSTONE_PORT_VERSION
          value: 5000/v3
        - name: VOLUME_PORT_VERSION
          value: 8776/v3
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: usageuser
              name: secretenv
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: usagepass
              name: secretenv
        - name: USER_PROJECT
          value: 5ad86ff5ec9d469ab2910103d6f9edd
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: usage-report
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: usage-report
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8006"
        - name: MS_CUSTOMER_CONTRACT
          value: http://customer-contract:8023
        - name: VOLUME_TYPE
          value: ORACLE-HANA
        - name: LOG_TARGET
          value: both
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/usage-report:46
        imagePullPolicy: IfNotPresent
        name: usage-report
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8006
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8006
          protocol: TCP
