apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/usage-report usage-report=10.81.1.72:5000/usage-report:19
      --record=true
  creationTimestamp: "2021-01-14T05:57:50Z"
  generation: 18
  labels:
    io.kompose.service: usage-report
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"DB_LINK"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KEYSTONE_PORT_VERSION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OPENSTACK_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PASSWORD"}:
                    .: {}
                    f:name: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USER_PROJECT"}:
                    .: {}
                    f:name: {}
                  k:{"name":"USERNAME"}:
                    .: {}
                    f:name: {}
                  k:{"name":"VOLUME_PORT_VERSION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8006,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:50Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:23:49Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                f:env:
                  k:{"name":"PASSWORD"}:
                    f:value: {}
                  k:{"name":"USER_PROJECT"}:
                    f:value: {}
                  k:{"name":"USERNAME"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-02-11T06:41:35Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-11T06:41:40Z"
  name: usage-report
  namespace: default
  resourceVersion: "5591755"
  uid: 0dc0b7a5-346c-4035-8759-e5038b5ecf97
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: usage-report
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: usage-report
    spec:
      containers:
      - env:
        - name: PORT
          value: "8006"
        - name: DB_LINK
          value: mongodb://10.81.1.72:27017
        - name: OPENSTACK_URL
          value: http://10.81.1.100
        - name: KEYSTONE_PORT_VERSION
          value: 5000/v3
        - name: VOLUME_PORT_VERSION
          value: 8776/v3
        - name: USERNAME
          value: DCM
        - name: PASSWORD
          value: letmein
        - name: USER_PROJECT
          value: 1d1709f19fd847bc82d75f3cf074fb04
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: usage-report
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: usage-report
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8006"
        - name: LOG_TARGET
          value: both
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        image: 10.81.1.72:5000/usage-report:19
        imagePullPolicy: IfNotPresent
        name: usage-report
        ports:
        - containerPort: 8006
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-21T06:46:37Z"
    lastUpdateTime: "2021-01-21T06:46:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-14T06:23:49Z"
    lastUpdateTime: "2021-02-11T06:41:40Z"
    message: ReplicaSet "usage-report-7bfb9dff85" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
