apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"29","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/usage-report usage-report=10.81.1.50:5000/usage-report:42 --record=true"},"creationTimestamp":"2020-10-19T13:17:10Z","generation":30,"labels":{"io.kompose.service":"usage-report"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"usage-report\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"APM_SERVER_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DB_LINK\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"KEYSTONE_PORT_VERSION\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOG_TARGET\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_CUSTOMER_CONTRACT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_CUSTOMER_INTEGRATION\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_SECRET_KEY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_LOGGER_THIS_SERVICE_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OPENSTACK_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"PASSWORD\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"USERNAME\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"USER_PROJECT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"VOLUME_PORT_VERSION\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"VOLUME_TYPE\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8006,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T11:36:07Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T11:36:16Z"}],"name":"usage-report","namespace":"default","resourceVersion":"27903849","selfLink":"/apis/apps/v1/namespaces/default/deployments/usage-report","uid":"e8bd53e0-4f75-488e-9ae0-71fe038d4301"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"usage-report"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"usage-report"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"8006"},{"name":"DB_LINK","value":"mongodb://10.81.1.50:27017"},{"name":"OPENSTACK_URL","value":"http://cloud2.ivlab.io"},{"name":"KEYSTONE_PORT_VERSION","value":"5000/v3"},{"name":"VOLUME_PORT_VERSION","value":"8776/v3"},{"name":"USERNAME","valueFrom":{"secretKeyRef":{"key":"ADMIN_USERNAME","name":"admin-user"}}},{"name":"PASSWORD","valueFrom":{"secretKeyRef":{"key":"ADMIN_PASSWORD","name":"admin-user"}}},{"name":"USER_PROJECT","value":"5ad86ff5ec9d469ab2910103d6f9edd"},{"name":"MS_LOGGER_THIS_SERVICE_NAME","value":"usage-report"},{"name":"MS_LOGGER_THIS_SERVICE_IP","value":"usage-report"},{"name":"MS_LOGGER_THIS_SERVICE_PORT","value":"8006"},{"name":"MS_CUSTOMER_CONTRACT","value":"http://customer-contract:8023"},{"name":"VOLUME_TYPE","value":"ORACLE-HANA"},{"name":"LOG_TARGET","value":"both"},{"name":"MS_LOGGER_SECRET_KEY","value":"BC2B36B81AB89F3B83AD227DCAD56"},{"name":"APM_SERVER_URL","value":"http://10.81.1.96:8200"},{"name":"ENVIRONMENT","value":"qa"}],"image":"10.81.1.50:5000/usage-report:42","imagePullPolicy":"IfNotPresent","name":"usage-report","ports":[{"containerPort":8006,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-11-04T05:36:12Z","lastUpdateTime":"2020-11-04T05:36:12Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-12-31T12:06:45Z","lastUpdateTime":"2021-03-03T11:36:16Z","message":"ReplicaSet \"usage-report-fd47877b4\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":30,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/usage-report usage-report=10.82.3.2:5000/usage-report:41
      --record=true
  creationTimestamp: "2021-03-15T07:09:05Z"
  generation: 7
  labels:
    io.kompose.service: usage-report
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                f:env:
                  k:{"name":"MS_CUSTOMER_INTEGRATION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
    manager: kubectl
    operation: Update
    time: "2021-03-03T11:36:07Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"APM_SERVER_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"DB_LINK"}:
                    .: {}
                    f:name: {}
                  k:{"name":"ENVIRONMENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KEYSTONE_PORT_VERSION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LOG_TARGET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_CUSTOMER_CONTRACT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_LOGGER_THIS_SERVICE_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OPENSTACK_URL"}:
                    .: {}
                    f:name: {}
                  k:{"name":"PASSWORD"}:
                    .: {}
                    f:name: {}
                  k:{"name":"PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USER_PROJECT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USERNAME"}:
                    .: {}
                    f:name: {}
                  k:{"name":"VOLUME_PORT_VERSION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"VOLUME_TYPE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8006,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:05Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:23:56Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"usage-report"}:
                f:env:
                  k:{"name":"APM_SERVER_URL"}:
                    f:value: {}
                  k:{"name":"DB_LINK"}:
                    f:value: {}
                  k:{"name":"OPENSTACK_URL"}:
                    f:value: {}
                  k:{"name":"PASSWORD"}:
                    f:value: {}
                  k:{"name":"USERNAME"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-19T13:32:44Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:03Z"
  name: usage-report
  namespace: default
  resourceVersion: "2198046"
  selfLink: /apis/apps/v1/namespaces/default/deployments/usage-report
  uid: 2754a93a-7a44-4037-9c78-b388d8102620
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: usage-report
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: usage-report
    spec:
      containers:
      - env:
        - name: PORT
          value: "8006"
        - name: DB_LINK
          value: mongodb://10.82.3.2:27017
        - name: OPENSTACK_URL
          value: http://cloud1.ivlab.io
        - name: KEYSTONE_PORT_VERSION
          value: 5000/v3
        - name: VOLUME_PORT_VERSION
          value: 8776/v3
        - name: USERNAME
          value: admin-user
        - name: PASSWORD
          value: password
        - name: USER_PROJECT
          value: 5ad86ff5ec9d469ab2910103d6f9edd
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: usage-report
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: usage-report
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8006"
        - name: MS_CUSTOMER_CONTRACT
          value: http://customer-contract:8023
        - name: VOLUME_TYPE
          value: ORACLE-HANA
        - name: LOG_TARGET
          value: both
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: APM_SERVER_URL
          value: http://10.82.3.7:8200
        - name: ENVIRONMENT
          value: qa
        image: 10.82.3.2:5000/usage-report:41
        imagePullPolicy: IfNotPresent
        name: usage-report
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8006
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-19T13:30:44Z"
    lastUpdateTime: "2021-03-19T13:32:46Z"
    message: ReplicaSet "usage-report-7bcf76496f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:03Z"
    lastUpdateTime: "2021-03-25T13:34:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
