apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"82","kompose.cmd":"kompose convert","kompose.version":"1.16.0 (0c01309)","kubernetes.io/change-cause":"kubectl set image deployment/webclient webclient=10.81.1.50:5000/webclient:390 --record=true"},"creationTimestamp":"2020-10-19T13:17:13Z","generation":83,"labels":{"io.kompose.service":"webclient"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kompose.cmd":{},"f:kompose.version":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}},"f:labels":{".":{},"f:io.kompose.service":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:name":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:name":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"webclient\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"API_GATEWAY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"BEFFE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DEVELOPMENT_ENV\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"EMAILER\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"IAM\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"IP_ADDR\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MONITORING_SOCKET_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MS_HYSTAX_IP\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ORCH\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":80,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl","operation":"Update","time":"2021-03-03T13:31:54Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-03-03T13:32:13Z"}],"name":"webclient","namespace":"default","resourceVersion":"27920969","selfLink":"/apis/apps/v1/namespaces/default/deployments/webclient","uid":"35dcd6b8-6b3c-4665-8b2f-540f509efc70"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"webclient"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"webclient"}},"spec":{"containers":[{"env":[{"name":"IP_ADDR","value":"10.81.1.50"},{"name":"BEFFE","value":"BEFFE"},{"name":"ORCH","value":"http://python-app:8002"},{"name":"IAM","value":"http://iam:8003"},{"name":"API_GATEWAY","value":"http://app.ivolve.io:30627"},{"name":"EMAILER","value":"http://emailer:8009"},{"name":"DEVELOPMENT_ENV","value":"true"},{"name":"MONITORING_SOCKET_IP","value":"http://app.ivolve-monitoring.io:30627"},{"name":"MS_HYSTAX_IP","value":"http://hystax:8015"}],"image":"10.81.1.50:5000/webclient:390","imagePullPolicy":"IfNotPresent","name":"webclient","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-02-10T11:54:55Z","lastUpdateTime":"2021-02-10T11:54:55Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-10-19T14:00:10Z","lastUpdateTime":"2021-03-03T13:32:13Z","message":"ReplicaSet \"webclient-57d54fccdb\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":83,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/webclient webclient=10.82.3.2:5000/webclient:372
      --record=true
  creationTimestamp: "2021-03-15T07:09:05Z"
  generation: 10
  labels:
    io.kompose.service: webclient
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"webclient"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"API_GATEWAY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"BEFFE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DEVELOPMENT_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"EMAILER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IAM"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IP_ADDR"}:
                    .: {}
                    f:name: {}
                  k:{"name":"MONITORING_SOCKET_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_HYSTAX_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ORCH"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-15T07:09:05Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"webclient"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-03-16T05:26:58Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"webclient"}:
                f:env:
                  k:{"name":"IP_ADDR"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-17T10:47:44Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-25T13:34:00Z"
  name: webclient
  namespace: default
  resourceVersion: "2197911"
  selfLink: /apis/apps/v1/namespaces/default/deployments/webclient
  uid: 43a46cf6-ccb7-438e-9376-8d752cf69107
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: webclient
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: webclient
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 10.82.3.2
        - name: BEFFE
          value: BEFFE
        - name: ORCH
          value: http://python-app:8002
        - name: IAM
          value: http://iam:8003
        - name: API_GATEWAY
          value: http://app.ivolve.io:30627
        - name: EMAILER
          value: http://emailer:8009
        - name: DEVELOPMENT_ENV
          value: "true"
        - name: MONITORING_SOCKET_IP
          value: http://app.ivolve-monitoring.io:30627
        - name: MS_HYSTAX_IP
          value: http://hystax:8015
        image: 10.82.3.2:5000/webclient:372
        imagePullPolicy: IfNotPresent
        name: webclient
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T05:26:58Z"
    lastUpdateTime: "2021-03-22T08:24:36Z"
    message: ReplicaSet "webclient-557c6f6f6c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-25T13:34:00Z"
    lastUpdateTime: "2021-03-25T13:34:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
