apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: webclient
  name: webclient
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webclient
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: webclient
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 10.82.3.2
        - name: BEFFE
          value: BEFFE
        - name: ORCH
          value: http://python-app:8002
        - name: IAM
          value: http://iam:8003
        - name: API_GATEWAY
          value: http://app.ivolve.io:30627
        - name: EMAILER
          value: http://emailer:8009
        - name: DEVELOPMENT_ENV
          value: "true"
        - name: MONITORING_SOCKET_IP
          value: http://app.ivolve-monitoring.io:30627
        - name: MS_HYSTAX_IP
          value: http://hystax:8015
        image: 10.82.3.2:5000/webclient:395
        imagePullPolicy: IfNotPresent
        name: webclient
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
