apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "31"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    kubernetes.io/change-cause: kubectl set image deployment/webclient webclient=10.81.1.72:5000/webclient:39
      --record=true
  creationTimestamp: "2021-01-14T05:57:51Z"
  generation: 31
  labels:
    io.kompose.service: webclient
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kompose.cmd: {}
          f:kompose.version: {}
        f:labels:
          .: {}
          f:io.kompose.service: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"webclient"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"API_GATEWAY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"BEFFE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DEVELOPMENT_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"EMAILER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IAM"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"IP_ADDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MONITORING_SOCKET_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MS_HYSTAX_IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ORCH"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-create
    operation: Update
    time: "2021-01-14T05:57:51Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubernetes.io/change-cause: {}
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"webclient"}:
                f:image: {}
    manager: kubectl-set
    operation: Update
    time: "2021-01-14T06:30:25Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-15T18:48:01Z"
  name: webclient
  namespace: default
  resourceVersion: "6117959"
  uid: 7e3d1362-8454-4eb3-8e31-d6629c584adb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: webclient
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: webclient
    spec:
      containers:
      - env:
        - name: IP_ADDR
          value: 10.81.1.72
        - name: BEFFE
          value: BEFFE
        - name: ORCH
          value: http://python-app:8002
        - name: IAM
          value: http://iam:8003
        - name: API_GATEWAY
          value: http://app.ivolve.io:30627
        - name: EMAILER
          value: http://emailer:8009
        - name: DEVELOPMENT_ENV
          value: "true"
        - name: MONITORING_SOCKET_IP
          value: http://app.ivolve-monitoring.io:30627
        - name: MS_HYSTAX_IP
          value: http://hystax:8015
        image: 10.81.1.72:5000/webclient:39
        imagePullPolicy: IfNotPresent
        name: webclient
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-14T06:30:25Z"
    lastUpdateTime: "2021-02-04T07:04:11Z"
    message: ReplicaSet "webclient-7c8dbd74f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-02-15T18:48:01Z"
    lastUpdateTime: "2021-02-15T18:48:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 31
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
